@categoryId = 1
@search = T-Shirt
@merchantId = 1

### Find
GET {{API_URL}}/products
    Merchant-Id: {{merchantId}}

### Find by filter
GET {{API_URL}}/products?categoryId={{categoryId}}

### Find by search
GET {{API_URL}}/products?search={{search}}

### Find by search and category
GET {{API_URL}}/products?search={{search}}&categoryId={{categoryId}}
